module.exports = {
    ConsentModel: require("./HL7/ConsentModel").getConsentModel(),
    ContractModel: require("./HL7/ContractModel").getContractModel(),
    GroupModel: require("./HL7/GroupModel").getGroupModel(),
    OrganizationModel: require("./HL7/OrganizationModel").getOrganizationModel(),
    PatientModel: require("./HL7/PatientModel").getPatientModel(),
    PlanDefinitionModel: require("./HL7/PlanDefinitionModel").getPlanDefinitionModel(),
    PractitionerModel: require("./HL7/PractitionerModel").getPractitionerModel(),
    PractitionerRoleModel: require("./HL7/PractitionerRoleModel").getPractitionerRoleModel(),
    QuestionnaireModel: require("./HL7/QuestionnaireModel").getQuestionnaireModel(),
    QuestionnaireResponseModel: require("./HL7/QuestionnaireResponseModel").getQuestionnaireResponseModel(),
    RelatedPersonModel: require("./HL7/RelatedPersonModel").getRelatedPersonModel(),
    ResearchStudyModel: require("./HL7/ResearchStudyModel").getResearchStudyModel(),
    ResearchSubjectModel: require("./HL7/ResearchSubjectModel").getResearchSubjectModel(),
    setHL7TrialConsent: require("./HL7/TrialConsentModel").setHL7TrialConsent,
    setHL7SiteConsent: require("./HL7/SiteConsentModel").setHL7SiteConsent,
    revertTrialConsent: require("./HL7/TrialConsentModel").revertTrialConsent,
    revertSiteConsent: require("./HL7/SiteConsentModel").revertSiteConsent,
    setHL7TrialResearchStudy: require("./HL7/TrialModel.js").getTrialResearchStudy,
    revertHL7TrialResearchStudy: require("./HL7/TrialModel.js").getStandardTrial,
    setSiteHL7Organization: require("./HL7/ClinicalSiteModel.js").getSiteHL7Organization,
    revertStandardClinicalSiteData: require("./HL7/ClinicalSiteModel.js").getStandardClinicalSiteData,
};