const QuestionnaireService = require("./services/iot/QuestionnaireService");
module.exports = {
    DidService:require("./services/DidService"),
    CommunicationService: require("./services/CommunicationService"),
    DPService:require("./services/iot/DPService"),
    MessageHandlerService: require("./services/MessageHandlerService"),
    DateTimeService: require("./services/DateTimeService"),
    DSUService: require("./services/DSUService"),
    SharedStorage: require("./services/SharedStorage"),
    JWTService: require("./services/JWTService"),
    BaseRepository: require("./repositories/BaseRepository"),
    Constants: require("./utils/Constants"),
    ConsentStatusMapper: require("./utils/ConsentStatusMapper"),
    momentService: require('./utils/moment.min'),
    FileDownloaderService: require("./utils/FileDownloaderService"),
    PDFService: require("./utils/PDFService"),
    HeaderController: require("./utils/HeaderController"),
    ResultsService:require("./services/iot/ResultsService"),
    FeedbackService: require("./services/iot/FeedbackService"),
    DeviceServices: require("./services/iot/DeviceServices"),
    QuestionnaireService: require("./services/iot/QuestionnaireService"),
    DeviceAssignationService: require("./services/iot/DeviceAssignationService"),
    HealthDataService: require ("./services/iot/HealthDataService"),
    PermissionedHealthDataService: require("./services/iot/PermissionedHealthDataService"),
    StudiesService: require("./services/iot/StudiesService"),
    StudyNotesService: require("./services/iot/StudyNotesService"),
    ResponsesService: require("./services/iot/ResponsesService"),
    models: require("./models"),
    getDataSourceFactory: () => require("./factories/DataSourceFactory"),
    getBreadCrumbManager: () => require("./others/BreadCrumbManager")
};